version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host=0.0.0.0 --port=5001
    expose:
      - 5001
    depends_on:
      - db
    ports:
      - "5001:5001"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
