"""Initial migrations 2

Revision ID: 4e9be4fbc44d
Revises: 694135774cf1
Create Date: 2022-03-23 19:25:21.191481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9be4fbc44d'
down_revision = '694135774cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
