"""Initial migrations

Revision ID: 694135774cf1
Revises: 
Create Date: 2022-03-23 19:23:03.860952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694135774cf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
