"""Initial migrations 4

Revision ID: cfac105b681c
Revises: 7b7b56dc8111
Create Date: 2022-03-23 19:40:29.496796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfac105b681c'
down_revision = '7b7b56dc8111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divorce_prediction_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hate_subject', sa.Integer(), nullable=True),
    sa.Column('happy', sa.Integer(), nullable=True),
    sa.Column('dreams', sa.Integer(), nullable=True),
    sa.Column('freedom_value', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('calm_breaks', sa.Integer(), nullable=True),
    sa.Column('harmony', sa.Integer(), nullable=True),
    sa.Column('roles', sa.Integer(), nullable=True),
    sa.Column('inner_world', sa.Integer(), nullable=True),
    sa.Column('current_stress', sa.Integer(), nullable=True),
    sa.Column('friends_social', sa.Integer(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('insult', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divorce_prediction_request_id'), 'divorce_prediction_request', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_divorce_prediction_request_id'), table_name='divorce_prediction_request')
    op.drop_table('divorce_prediction_request')
    # ### end Alembic commands ###
