"""Initial migrations

Revision ID: f327cd3f47ff
Revises: 
Create Date: 2022-03-25 21:04:44.688591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f327cd3f47ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('divorce_prediction_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hate_subject', sa.Integer(), nullable=True),
    sa.Column('happy', sa.Integer(), nullable=True),
    sa.Column('dreams', sa.Integer(), nullable=True),
    sa.Column('freedom_value', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('calm_breaks', sa.Integer(), nullable=True),
    sa.Column('harmony', sa.Integer(), nullable=True),
    sa.Column('roles', sa.Integer(), nullable=True),
    sa.Column('inner_world', sa.Integer(), nullable=True),
    sa.Column('current_stress', sa.Integer(), nullable=True),
    sa.Column('friends_social', sa.Integer(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('insult', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divorce_prediction_request_id'), 'divorce_prediction_request', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_divorce_prediction_request_id'), table_name='divorce_prediction_request')
    op.drop_table('divorce_prediction_request')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
